language: ruby
rvm:
  - 2.2.1
  - rbx
services:
  - postgresql
before_script:
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test
env:
  global:
    SAUCY: true
addons:
  sauce_connect:
    username:
      secure: "AfFUL22WY4YDTNCMSbR65TQ56R2zPCmKmH+LDOEgj8QaB+J9Yc2fqQ71hGIxHqpJ38c1Wn865icGfF73gWyS9fJG5gfmKH01/LbmVYb8N14T9rWYOtOTB8IUiEIIxVe15pIuOxQqt5yZ8le9TFgLoCPnv3Fg7vVviLL1m7S0Ctc+nyykAiJpXeO+eV2/uPmbo1L3hR7tm8CGOqFLXdCR0L8azxW0QVyXo+IuogJsWV0/MDQnmk9aej1kR1oVfBTNeCiGlA29itlFdIeHUNggisKWj5G+h+giCdcR/IU29nMWh9EGlt/rWgeutNCQOi5XI/VSVUwYp0yMqjPEjylQUyT4WPoRZc+qVyIK522WkXI3nw8r+KRCxi+IArXmbpZc5dHXP8ZerxslDI6yCSstGXC2pjuiKzl+8j68/NpQYZzzc16UAAzEgEYb0FmtqClszBphWSMQajY/6y6e1DXxxzg/E4cimJfoCcjGUh4hh7fCEtQUBznE+8MBiMUGOdibMtC7h2hYAd9oTZLVXeN7tpJ2iRni3UesZKSATbuSMvBt4J6VFZqAq3hyBbYe/NoJCgP5A5zQpyjxpKBSCH7b22lgcEtALjI3cwsp3gueQ92sM58hfPGXuST7l43Mk4H0aosG81QXYFqNGKb/cdJmaN/0XEa2dJd4eMuBNNhQHok="
    access_key:
      secure: "gMog33hCsNHkE9lfZpVeY/yRD89f1INL9FrFyMv+2g94KJLV/BSrFVemuVzk2JklTcIwW775/pMJLVmBonUgInxGX7b5d98Hp5MO7keQVJ2qU6zCnqAvt+qmIplF9EeF6AZraMaamiD/ZNok15yHlk2sGnj4PhffKkf2E3vBw9GHNJeipH5HTjQ0n7/zVay3KNzDTXzFjihOJeC6GnPx8Yvd/hIEZRbojxFUBV7RV4Q39/IhAlM3729EOybOQnAB+UN+C1hDbTk7/29R3iPAnCcMNrJYxcOYtaxfSUXw6inTBK+bA1pCmCbFmB1wDSnuVfC98oRR0rH3uPeZDkV8RwRNZb1GtFJR9E7BhsqiTSXjTBZXTDZdIhd8tjaJ0x8CwVgacTh6sim92GDkBVZ53hTFoLkd3A66uHHpr0cdthEVH6i/OUz8InBB0BwOqa5AvEfR5JUqjX+TlgDf6OfcdCTIXjVsPMnHeT10XvZmAa4bZ/OOxrRuULD32fUE+BcIVpTPsmjbqdYbamyDndHE6pQxIu2Fby1mwx/m+5mQlFO6RBhbEz/TnZZbFmJQ+AOSW/i/HLj6IrSsmqwYkmWVDVKaiXaZE8JhFnIVJ5WjPprtIQ8fh9jloWBt1/mR0Tuk7T3dJC8pRROf/DBmC2r3N3IgVfjglFH+dwA+Y7GcUuY="
