# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f1192c36c5769befb4a0ee5ff811a7f9afb92bad1cd663626cfbb658df75cd7c37ebbe8dac550d4fb71c1483542b3f067eb68db9407d0da6e600b13b20a2b6a

test:
  secret_key_base: 30e94471851239db0e04387ed60a0fb9fa566812ce35d1a7db3e415103a3da34d84a8a7b91049f155575f250fea1d9ffe57508636940c4773db12a89bf3bed2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
